### ISSUE TITLE
`getPositionalArg` should allow `required`

### ISSUE THREAD

**Issue by lexisother** [marshift/argus#1]
As the title says, context's function is missing `required` param.
https://github.com/marshift/argus/blob/99c97623c56d41a40fcdfa8454279a875801939b/src/index.ts#L58

**Comment by marshift** [comment]
hi - i've just fixed this in version 1.1.0 of the library (commit [7daa9ea](https://github.com/marshift/argus/commit/7daa9ea1864b9858a991075a4d4d1a6d4e1d6c40)). apologies for the delay on this!
